import { EventEmitter } from "events";

export const EVENT_REQUEST_CONFIRM = "EVENT_REQUEST_CONFIRM";
export const EVENT_REQUEST_CONFIRM_APPROVED = "EVENT_REQUEST_CONFIRM_APPROVED";
export const EVENT_REQUEST_CONFIRM_REJECTED = "EVENT_REQUEST_CONFIRM_REJECTED";
export const EVENT_APPROVED_ACTION_RESPONSE = "EVENT_APPROVED_ACTION_RESPONSE";
export const EVENT_HANDLE_RPC_REQUEST = "EVENT_HANDLE_RPC_REQUEST";
export const EVENT_HANDLE_RPC_RESPONSE = "EVENT_HANDLE_RPC_RESPONSE";

export enum EVENT_TYPE {
  OPEN_NEWTAB_BROWSER = "OPEN_NEWTAB_BROWSER",
  WALLET_CONNECT_NEW_SESSION = "WALLET_CONNECT_NEW_SESSION",
  DAPP_CONNECT_REQUEST = "DAPP_CONNECT_REQUEST",
  CONFIRM_TRANSACTION = "CONFIRM_TRANSACTION",
}

export class EventHub extends EventEmitter {
  constructor() {
    super();
  }
}

// export const eventHub = new EventEmitter();
